-- UPDATE문에 사용되는 서브쿼리 
-- TB_EMP 테이블에 DEPT_NM 컬럼을 추가하고 
-- UPDATE문 사용하여 DEPT_NM의 값을 일괄적으로 UPDATE

SELECT *
FROM TB_EMP
;

ALTER TABLE TB_EMP ADD(DEPT_NM VARCHAR2(150));

UPDATE TB_EMP A
SET A.DEPT_NM = (
					SELECT K.DEPT_NM 
					FROM TB_DEPT K
					WHERE A.DEPT_CD = K.DEPT_CD 
				)
;

-- 다시 원래 테이블 형태로 돌려놓기 (삭제처리)
ALTER TABLE TB_EMP DROP COLUMN DEPT_NM;


-- INSERT문에 사용되는 서브쿼리
CREATE TABLE INSERT_SUBQUERY_TEST
(
	EMP_NO	CHAR(10)
	, MAX_PAY_AMT	NUMBER(15)
)
;

SELECT * FROM INSERT_SUBQUERY_TEST;

-- 사원 번호가 "1000000001"인 직원의 최고 급여를 삽입하기 

SELECT MAX(PAY_AMT) 
FROM TB_SAL_HIS 
WHERE EMP_NO = '1000000001'
;

INSERT INTO INSERT_SUBQUERY_TEST VALUES (
					'1000000001'
					,(SELECT MAX(PAY_AMT) FROM TB_SAL_HIS WHERE EMP_NO = '1000000001')
)
;


-- 뷰생성
SELECT A.EMP_NO, A.EMP_NM , B.DEPT_CD , B.DEPT_NM
	,MAX(C.PAY_AMT) AS MAX_PAY_AMT 
FROM TB_EMP A, TB_DEPT B, TB_SAL_HIS C
WHERE A.DEPT_CD = B.DEPT_CD 
 AND A.EMP_NO = C.EMP_NO 
GROUP BY A.EMP_NO, A.EMP_NM , B.DEPT_CD , B.DEPT_NM 
;

CREATE VIEW V_TB_SAL_HIS_MAX_BY_EMP_NO
AS 
SELECT A.EMP_NO, A.EMP_NM , B.DEPT_CD , B.DEPT_NM
	,MAX(C.PAY_AMT) AS MAX_PAY_AMT 
FROM TB_EMP A, TB_DEPT B, TB_SAL_HIS C
WHERE A.DEPT_CD = B.DEPT_CD 
 AND A.EMP_NO = C.EMP_NO 
GROUP BY A.EMP_NO, A.EMP_NM , B.DEPT_CD , B.DEPT_NM 
;

SELECT *
FROM V_TB_SAL_HIS_MAX_BY_EMP_NO
;

SELECT *
FROM V_TB_SAL_HIS_MAX_BY_EMP_NO
WHERE MAX_PAY_AMT >= 5910000 
;

DROP VIEW V_TB_SAL_HIS_MAX_BY_EMP_NO;















