SELECT 
	DUMMY 
FROM DUAL 
;

-- SYSTEM 계정으로 접속 
-- 오라클 18c에서 사용자 계정 생성을 위한 설정
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- 신규 사용자 계정 생성 (기존에 존재하면 제거 후 다시 생성)
-- HM 사용자 계정 및 테이블 스페이스를 제거함 
-- 기존에 존재하지 않는다면 에러가 발생함. 에러 발생해도 무시하면 됨 
DROP USER HM CASCADE;
DROP TABLESPACE HM_DATA INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE HM_TEMP INCLUDING CONTENTS AND DATAFILES;

-- "HM" 사용자 계정을 생성
CREATE USER HM IDENTIFIED BY 0305;
ALTER USER HM ACCOUNT UNLOCK;
-- "HM" 사용자 계정에게 권한 주기
GRANT RESOURCE, DBA, CONNECT TO HM;

-- 테이블 스페이스 생성
CREATE TABLESPACE HM_DATA
DATAFILE 'C:\app\pc-555\product\18.0.0\oradata\XE\HM_DATA.DBF' SIZE 1G
AUTOEXTEND ON NEXT 512M MAXSIZE UNLIMITED 
LOGGING
ONLINE 
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO 
FLASHBACK ON;

CREATE TEMPORARY TABLESPACE HM_TEMP
TEMPFILE 'C:\app\pc-555\product\18.0.0\oradata\XE\HM_TEMP.DBF' SIZE 100M
AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

-- HM 사용자 계정의 디폴트 테이블 스페이스 설정
ALTER USER HM DEFAULT TABLESPACE HM_DATA;
ALTER USER HM TEMPORARY TABLESPACE HM_TEMP;














