-- CREATE TABLE 
-- TB_DEPT_TEMP 테이블 생성
DROP TABLE HM.TB_DEPT_TEMP PURGE;
CREATE TABLE HM.TB_DEPT_TEMP
(
	DEPT_CD CHAR(6) NOT NULL
	, DEPT_NM VARCHAR2(150) NOT NULL
	, UPPER_DEPT_CD CHAR(6)
);

-- TB_DEPT_TEMP 테이블 기본 키 생성
ALTER TABLE HM.TB_DEPT_TEMP 
	ADD CONSTRAINT PK_TB_DEPT_TEMP PRIMARY KEY (DEPT_CD);