-- SYSTEM 계정으로 접속 
-- 오라클 18c에서 사용자 계정 생성을 위한 설정
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- 신규 사용자 계정 생성 (기존에 존재하면 제거 후 다시 생성)
-- OT 사용자 계정 및 테이블 스페이스를 제거함 
-- 기존에 존재하지 않는다면 에러가 발생함. 에러 발생해도 무시하면 됨 
DROP USER OT CASCADE;
DROP TABLESPACE OT_DATA INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE OT_TEMP INCLUDING CONTENTS AND DATAFILES;

-- "OT" 사용자 계정을 생성
CREATE USER OT IDENTIFIED BY 0305;
ALTER USER OT ACCOUNT UNLOCK;
-- "OT" 사용자 계정에게 권한 주기
GRANT RESOURCE, DBA, CONNECT TO OT;

-- 테이블 스페이스 생성
CREATE TABLESPACE OT_DATA
DATAFILE 'C:\app\pc-555\product\18.0.0\oradata\XE\OT_DATA.DBF' SIZE 1G
AUTOEXTEND ON NEXT 512M MAXSIZE UNLIMITED 
LOGGING
ONLINE 
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO 
FLASHBACK ON;

CREATE TEMPORARY TABLESPACE OT_TEMP
TEMPFILE 'C:\app\pc-555\product\18.0.0\oradata\XE\OT_TEMP.DBF' SIZE 100M
AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

-- OT 사용자 계정의 디폴트 테이블 스페이스 설정
ALTER USER OT DEFAULT TABLESPACE OT_DATA;
ALTER USER OT TEMPORARY TABLESPACE OT_TEMP;







