-- CREATE TABLE 
-- TB_DEPT_TEMP 테이블 생성
DROP TABLE HM.TB_DEPT_TEMP PURGE;
CREATE TABLE HM.TB_DEPT_TEMP
(
	DEPT_CD CHAR(6) NOT NULL
	, DEPT_NM VARCHAR2(150) NOT NULL
	, UPPER_DEPT_CD CHAR(6)
);

-- TB_DEPT_TEMP 테이블 기본 키 생성
ALTER TABLE HM.TB_DEPT_TEMP 
	ADD CONSTRAINT PK_TB_DEPT_TEMP PRIMARY KEY (DEPT_CD);
	

DROP TABLE HM.TB_EMP_TEMP PURGE;
CREATE TABLE HM.TB_EMP_TEMP
(
	EMP_NO	CHAR(10) NOT NULL
	, EMP_NM	VARCHAR2(150) NOT NULL
	, BIRTH_DE	CHAR(8)	NOT NULL
	, LUNAR_YN	CHAR(1)	NOT NULL
	, SEX_CD  CHAR(3) NOT NULL
	, ADDR 	VARCHAR2(1000) NOT NULL
	, TEL_NO VARCHAR2(150) NOT NULL
	, FINAL_EDU_SE_CD CHAR(3) NOT NULL
	, SAL_TRANS_BANK_CD CHAR(3) NOT NULL
	, SAL_TRANS_ACCNT_NO VARCHAR2(20) NOT NULL
	, DIRECT_MANAGER_EMP_NO CHAR(10)
	, DEPT_CD CHAR(6) NOT NULL
);









